//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int ID { get; set; }
        public Nullable<int> ServiceRef { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
    
        public virtual ItemsInfo ItemsInfo { get; set; }
        public virtual ServiceRecordInfo ServiceRecordInfo { get; set; }
    }
}
