//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRecordInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRecordInfo()
        {
            this.BillInfoes = new HashSet<BillInfo>();
        }
    
        public int ServiceRefNo { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> ModalNo { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public Nullable<int> ServiceRepId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillInfo> BillInfoes { get; set; }
        public virtual CustomerMaster CustomerMaster { get; set; }
        public virtual VechileMaster VechileMaster { get; set; }
        public virtual ServiceRepInfo ServiceRepInfo { get; set; }
    }
}
